version: "2.2"
services: 
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./gamer-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ottria
  web:
    build: .
    ports:
      - 8080:80
      - 8043:443
    volumes:
      - ./myphp:/var/www/html

